namespace ASP_Chat.Exceptions
{
    public enum ExceptionCodes
    {
        InternalServerError = 0,
        ValidationError,
        SecretKeyNotSet,
        EmptyCredentials,
        InvalidCredentials,
        InvalidToken,
        InvalidInput,
        UserNotFound,
        UserNotAdmin,
        UserNotInChat,
        UserCanNotLeaveChatAsAdmin,
        UserAlreadyExists,
        UserAlreadyInChat,
        UserAlreadyModerator,
        UsersNotFound,
        ChatNotFound,
        ChatNotPublic,
        ChatTypeNotFound,
        ChatCanNotHaveUsers,
        ChatCanNotHaveModerators,
        ChatCanNotBeUpdated,
        GroupNameIsEmpty,
        ChannelNameIsEmpty,
        ChannelTagIsEmpty,
        MessageNotFound,
        MessageIsEmpty,
        NoPermissionToSendMessage,
        NoPermissionToEditMessage,
        NoPermissionToDeleteMessage,
        FeldAreRequired,
    }
}
